# Generated by Django 3.1.5 on 2022-10-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='education_grade',
            field=models.CharField(blank=True, max_length=3, verbose_name='Это задание предназначено для класса:'),
        ),
        migrations.AlterField(
            model_name='mathuser',
            name='education_grade',
            field=models.CharField(max_length=3, verbose_name='Класс обучения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название работы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_deadline',
            field=models.DateTimeField(verbose_name='Дедлайн сдачи работы'),
        ),
    ]
