# Generated by Django 3.1.5 on 2022-10-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20221007_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='education_grade',
        ),
        migrations.RemoveField(
            model_name='work',
            name='performer',
        ),
        migrations.AddField(
            model_name='work',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Work Owner'),
        ),
        migrations.AddField(
            model_name='work',
            name='work_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='MathUser',
        ),
    ]
