# Generated by Django 3.1.5 on 2022-10-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20221013_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_deadline',
            new_name='deadline',
        ),
    ]
